"""add about table

Revision ID: efeee8d296a1
Revises: a36efc3124b1
Create Date: 2026-04-18 18:41:01.296215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efeee8d296a1'
down_revision: Union[str, None] = 'a36efc3124b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tagline', sa.String(length=300), nullable=False),
    sa.Column('bio_paragraphs', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('years_exp', sa.Integer(), nullable=False),
    sa.Column('projects_count', sa.Integer(), nullable=False),
    sa.Column('oss_packages', sa.Integer(), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('about')
    # ### end Alembic commands ###
